name: myapp_app
description: "A new Flutter project for showcasing a modern shopping app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo.PNG
    - lib/images/nike.JPG
    - lib/images/nike1.JPG
    - lib/images/nike2.JPG
    - lib/images/nike3.JPG
    - lib/images/nikelogo.PNG
    - lib/images/nikelogo1.png
    - lib/images/jordan.JPG
    - lib/images/jordan1.JPG
    - lib/images/jordan2.JPG
    - lib/images/jordan3.JPG
